### ISSUE TITLE
the module does not work for me when fully offline

### ISSUE THREAD

**Issue by amircogan** [besLisbeth/arcgis-offline-tiles#6] opened 2021-02-16 08:31 UTC
Hi,
I tried to use this module when fully offline (i.e. stop wifi on my laptop). But id does not work properly
The initial page loads with the menu of the layers (topo, streets, satellite etc) - the maps are blank but that is OK I guess - if I don't have any online access and no map in offline loaded yet.
However this is already in the console an error:

Uncaught (in promise) TypeError: Cannot read property 'getRecord' of undefined
    at Object.getAllTiles (main.c0f7b698d5d846dda85a.bundle.js:2)
    at t.<anonymous> (main.c0f7b698d5d846dda85a.bundle.js:2)
    at u (main.c0f7b698d5d846dda85a.bundle.js:2)
    at Generator._invoke (main.c0f7b698d5d846dda85a.bundle.js:2)
    at Generator.next (main.c0f7b698d5d846dda85a.bundle.js:2)
    at pe (main.c0f7b698d5d846dda85a.bundle.js:2)
    at a (main.c0f7b698d5d846dda85a.bundle.js:2)
    at main.c0f7b698d5d846dda85a.bundle.js:2
    at new Promise (<anonymous>)
    at t.<anonymous> (main.c0f7b698d5d846dda85a.bundle.js:2)

Next when I try to click on the "configuration wheel" icon of one of the layer, I get a blank white page and another error in the console:

Uncaught TypeError: Cannot read property 'lods' of null
    at x.get (main.c0f7b698d5d846dda85a.bundle.js:2)
    at x.value (main.c0f7b698d5d846dda85a.bundle.js:2)
    at new x (main.c0f7b698d5d846dda85a.bundle.js:2)
    at gi (main.c0f7b698d5d846dda85a.bundle.js:2)
    at Ra (main.c0f7b698d5d846dda85a.bundle.js:2)
    at vs (main.c0f7b698d5d846dda85a.bundle.js:2)
    at ul (main.c0f7b698d5d846dda85a.bundle.js:2)
    at sl (main.c0f7b698d5d846dda85a.bundle.js:2)
    at $s (main.c0f7b698d5d846dda85a.bundle.js:2)
    at main.c0f7b698d5d846dda85a.bundle.js:2

Background:
I am using the gh-pages branch (that one seems to be runable). To view the code I am using the demo-sources branch (although I think it is not quite the same)

Many Many thanks for your help

Amir

**Comment by besLisbeth** [comment] 2021-02-16 10:22
Hi, @amircogan. 
It's strange to me, that the demo didn't work out for you. Yes, branch `demo-pages` is the source code for the demo page (where you can look at how you can manipulate the extension), and `gh-pages` is `demo-pages` which was built by Webpack to serve as a separate page.
![image](https://user-images.githubusercontent.com/31760858/108049893-89b5ff80-7051-11eb-8f48-5c720377cb53.png)

The errors above are connected to the problems with indexedDB where all the tiles are loaded to work offline. What browser do you use? I tested everything on Google Chrome.
Thank you a lot for the nice words, I really hope, that everything will work out for you

**Comment by amircogan** [comment] 2021-02-16 20:47
Dear Yelyzaveta,

Thank you for responding so quickly and nicely.
First - it is a great piece of software, really great !!!
I also use chrome.
Here is how the problem happens:
I cloned the project and switched to gh-pages branch (git checkout gh-pages)
I put the files on my web server and connect with Chrome client to webserver
Everything works good when Internet connected
Also works good if I start with Internet connected and disconnect in the middle, but
If I disconnect internet and then open the page with "clean cache" (I use chrome devtools ) - to simulate a true offline state I get the error:

Uncaught (in promise) TypeError: Cannot read property 'getRecord' of undefined
at Object.getAllTiles (main.c0f7b698d5d846dda85a.bundle.js:2)
at t. (main.c0f7b698d5d846dda85a.bundle.js:2)
at u (main.c0f7b698d5d846dda85a.bundle.js:2)
at Generator._invoke (main.c0f7b698d5d846dda85a.bundle.js:2)
at Generator.next (main.c0f7b698d5d846dda85a.bundle.js:2)
at pe (main.c0f7b698d5d846dda85a.bundle.js:2)
at a (main.c0f7b698d5d846dda85a.bundle.js:2)
at main.c0f7b698d5d846dda85a.bundle.js:2
at new Promise ()
at t. (main.c0f7b698d5d846dda85a.bundle.js:2)

See attached: 
offline.jpg - how I clean cache after I disconnect Internet
offline_error.jpg - the errors I see then in the console
![offline_error](https://user-images.githubusercontent.com/12463145/108119296-3f13a200-70a8-11eb-91f1-2045fec74a28.JPG)
![offline](https://user-images.githubusercontent.com/12463145/108119299-4044cf00-70a8-11eb-919c-f049e9260b89.jpg)


Another question I have - assuming you tell me how to get rid of this problem - I want the downloaded and save tiles to be on my offline server (not on the offline client) . In my setup we have a network that is not connected to the internet . There is a web server and some clients connect to it. I want to use your code so web clients can see the map - but I think it should be stored on the server.

Many Thanks !!
   Amir

**Comment by besLisbeth** [comment] 2021-02-17 14:21
Ok, I understood the issue. 
So, the problem is in the cache cleaning. When you clean the cache you also destroy the internal indexedDB where all the tiles are uploaded. So, what you can do - you can try to create the mechanism of downloading all the tiles to the .csv file at the server and then upload it in the background for all the users. 

Here is the button for downloading the .csv, and below is the button for file selecting. You just need to change the code of the demo to make everything work without buttons.
![image](https://user-images.githubusercontent.com/31760858/108216742-7bdca900-713b-11eb-9bcc-c85df373237f.png)

**Comment by besLisbeth** [comment] 2021-02-22 06:46
@amircogan, I hope that I helped you to resolve the issue, so I'm closing it. I will be pleased if you rate my project with the star

**Closed as completed by besLisbeth** 2021-02-22 06:46 UTC

**Comment by amircogan** [comment] 2021-03-01 14:53
Thank you very much , sure I will star your project.
Regards,
